on:
  release:
    types:
      - created  

jobs:
  build:
    name: Build and upload binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build files
        run: |
          go mod tidy

          cat << 'EOF' > build.sh
          go build endlessh-go
          echo endlessh-go-${{ github.event.release.name }}-$1-$2.tar.gz
          archive_name=$(echo endlessh-go-${{ github.event.release.name }}-$1-$2.tar.gz)
          tar cfz $archive_name endlessh-go
          echo "archive_name_$1_$2=$archive_name" >> "$GITHUB_OUTPUT"
          EOF
          chmod +x build.sh
          cat build.sh

          ./build.sh linux amd64
          ./build.sh linux arm64
          ./build.sh darwin amd64
          ./build.sh darwin arm64
          ./build.sh windows amd64
          echo "archive_name_$GOOS_$GOARCH=$archive_name"
          ls -l
      - name: Upload Release Asset
        if: runner.os == 'Linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_linux.outputs.archive_name }}
          asset_name: ${{ steps.compress_linux.outputs.archive_name }}
          asset_content_type: application/gzip
