on:
  release:
    types:
      - created  

jobs:
  build:
    name: Build and upload binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build files
        run: |
          go mod tidy
          cat << 'EOF' > build.sh
          GOOS=$1 GOARCH=$2 go build endlessh-go
          archive_name=$(echo endlessh-go-${{ github.event.release.name }}-$1-$2.tar.gz)
          tar cfz $archive_name endlessh-go
          echo "archive_name_$1_$2=$archive_name" >> "$GITHUB_OUTPUT"
          EOF
          chmod +x build.sh
          ./build.sh linux amd64
          ./build.sh linux arm64
          ./build.sh darwin amd64
          ./build.sh darwin arm64
          ./build.sh windows amd64
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_linux.outputs.archive_name_linux_amd64 }}
          asset_name: ${{ steps.compress_linux.outputs.archive_name_linux_amd64 }}
          asset_content_type: application/gzip
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_linux.outputs.archive_name_linux_arm64 }}
          asset_name: ${{ steps.compress_linux.outputs.archive_name_linux_arm64 }}
          asset_content_type: application/gzip
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_linux.outputs.archive_name_darwin_amd64 }}
          asset_name: ${{ steps.compress_linux.outputs.archive_name_darwin_amd64 }}
          asset_content_type: application/gzip
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_linux.outputs.archive_name_darwin_arm64 }}
          asset_name: ${{ steps.compress_linux.outputs.archive_name_darwin_arm64 }}
          asset_content_type: application/gzip
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_linux.outputs.archive_name_windows_amd64 }}
          asset_name: ${{ steps.compress_linux.outputs.archive_name_windows_amd64 }}
          asset_content_type: application/gzip
